import { stringToParams } from "core";
import Link from 'next/link'
import styles from './seed.module.css'
import Seed from './seed'

type SeedParams = {
  seed: string
}

export default function SeedPage({ params }: { params: SeedParams}) {
  
  const SeedFooter = () => {
    return (
      <footer className={styles.footer}>
        <p>
          This seed was generated by
          <br />
          <Link href="/">DASH Randomizer</Link>
        </p>
      </footer>
    );
  };

  const settings = stringToParams(params.seed)
  return (
    <main className={styles.container}>
      <h1 className={styles.logo}>DASH</h1>
      <Seed parameters={settings} hash={params.seed} />
      <SeedFooter />
    </main>
  );
}
