export const mapLocation = (name) => {
  const mappings = [
    ["Missiles (Billy Mays 1)", ""],
    ["Missiles (Billy Mays 2)", ""],
    ["Missiles (Gauntlet Right)", ""],
    ["Missiles (Gauntlet Left)", ""],
    ["Energy Tank (Gauntlet)", ""],
    ["Energy Tank (Terminator)", ""],
    ["Missiles (230)", ""],
    ["Power Bombs (Landing Site)", ""],
    ["Supers (Climb)", ""],
    ["Missiles (Alpha)", ""],
    ["Missiles (Beta)", ""],
    ["Power Bombs (Morph)", ""],
    ["Energy Tank (Brinstar Ceiling)", ""],
    ["Missiles (Moat)", ""],
    ["Morphing Ball", ""],
    ["Missiles (Mother Brain)", ""],
    ["Bombs", ""],
    ["Reserve Tank (Wrecked Ship)", ""],
    ["Missiles (Bowling)", ""],
    ["Energy Tank (Wrecked Ship)", ""],
    ["Gravity Suit", ""],
    ["Supers (WS Right)", ""],
    ["Supers (WS Left)", ""],
    ["Missiles (Sky)", ""],
    ["Missiles (Spooky)", ""],
    ["Missiles (Attic)", ""],
    ["Missiles (Ocean Bottom)", ""],
    ["Missiles (Ocean Middle)", ""],
    ["Varia Suit", ""],
    ["Energy Tank (Kraid)", ""],
    ["Missiles (Kraid)", ""],
    ["Space Jump", ""],
    ["Energy Tank (Ridley)", ""],
    ["Charge Beam", ""],
    ["Energy Tank (Waterway)", ""],
    ["Missiles (Watering Hole)", ""],
    ["Plasma Beam", ""],
    ["Spring Ball", ""],
    ["Missiles (Mickey Mouse)", ""],
    ["Power Bombs (Alpha)", "PBs_Alpha"],
    ["Missiles (Alpha PBs)", "Missiles_AlphaPBs"],
    ["Power Bombs (Beta)", "PBs_Beta"],
    ["Power Bombs (Etecoons)", "PBs_Etecoons"],
    ["Energy Tank (Etecoons)", "EnergyTank_Etecoons"],
    ["Supers (Etecoons)", "Supers_Etecoons"],
    ["Supers (Spore Spawn)", "Supers_SpoSpo"],
    ["Missiles (Early Bridge)", "Missiles_EarlySupers"],
    ["Supers (Early Bridge)", "Supers_EarlySupers"],
    ["Reserve Tank (Brinstar)", "ReserveTank_Brinstar"],
    ["Missiles (Brin Reserve 2)", "Missiles_BrinstarReserve2"],
    ["Missiles (Brin Reserve 1)", "Missiles_BrinstarReserve1"],
    ["Missiles (Big Pink)", "Missiles_BigPink"],
    ["Missiles (Charge)", "Missiles_Charge"],
    ["Power Bombs (Mission Impossible)", "PBs_Impossible"],
    ["Missiles (Brin Tube)", "Missiles_Tube"],
    ["Energy Tank (Wave Gate)", "EnergyTank_WaveGate"],
    ["Energy Tank (Crocomire)", "EnergyTank_Croc"],
    ["Grapple Beam", "GrappleBeam"],
    ["Xray Scope", "XrayScope"],
    ["Spazer", "Spazer"],
    ["Missiles (Cosine)", "Missiles_Cosine"],
    ["Missiles (Indiana Jones)", "Missiles_IndianaJones"],
    ["Missiles (Croc Escape)", "Missiles_CrocEscape"],
    ["Power Bombs (Crocomire)", "PBs_Croc"],
    ["Energy Tank (Botwoon)", "EnergyTank_Botwoon"],
    ["Missiles (Aqueduct)", "Missiles_Aqueduct"],
    ["Supers (Aqueduct)", "Supers_Aqueduct"],
    ["Missiles (Precious)", "Missiles_Precious"],
    ["Missiles (Cathedral)", "Missiles_Cathedral"],
    ["Missiles (Mainstreet)", "Missiles_MainStreet"],
    ["Supers (Crab)", "Supers_Crab"],
    ["Energy Tank (Mama Turtle)", "EnergyTank_MamaTurtle"],
    ["Missiles (Mama Turtle)", "Missiles_MamaTurtle"],
    ["Supers (Watering Hole)", "Supers_WateringHole"],
    ["Missiles (Beach)", "Missiles_Beach"],
    ["Missiles (Sand Pit Left)", "Missiles_LeftSandPit"],
    ["Reserve Tank (Maridia)", "ReserveTank_LeftSandPit"],
    ["Missiles (Sand Pit Right)", "Missiles_RightSandPit"],
    ["Power Bombs (Sand Pit Right)", "PBs_RightSandPit"],
    ["Energy Tank (Firefleas)", "EnergyTank_Firefleas"],
    ["Ice Beam", "IceBeam"],
    ["Missiles (Crumble Shaft)", "Missiles_CrumbleShaft"],
    ["Missiles (GT)", "Missiles_GT"],
    ["Supers (GT)", "Supers_GT"],
    ["Missiles (Maze)", "Missiles_Maze"],
    ["Power Bombs (Maze)", "PBs_Maze"],
    ["HiJump Boots", "HiJumpBoots"],
    ["Missiles (HJB)", "Missiles_HiJump"],
    ["Energy Tank (HJB)", "EnergyTank_HiJump"],
    ["Reserve Tank (Norfair)", "ReserveTank_Norfair"],
    ["Missiles (Norfair Reserve 2)", "Missiles_NorfairReserve2"],
    ["Missiles (Norfair Reserve 1)", "Missiles_NorfairReserve1"],
    ["Missiles (Bubble Mountain)", "Missiles_BubbleMountain"],
    ["Missiles (Speed)", "Missiles_SpeedBooster"],
    ["Speed Booster", "SpeedBooster"],
    ["Missiles (Three Muskateers)", "Missiles_Muskateers"],
    ["Missiles (Wave)", "Missiles_Wave"],
    ["Wave Beam", "WaveBeam"],
    ["Power Bombs (Shame)", "PBs_Shame"],
    ["Screw Attack", "ScrewAttack"],
  ];

  const mapped = mappings.find((m) => m[0] == name);
  if (mapped != undefined) {
    if (mapped[1] == "") {
      return name;
    }
    return mapped[1];
  }
  throw new Error("missing " + name);
};
