import { JetBrains_Mono } from 'next/font/google';

const mono = JetBrains_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--jetbrains-mono',
});

export const metadata = {
  title: 'DASH Randomizer Seed',
  description: 'Seed generated by the Super Metroid DASH Randomizer',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className={mono.variable}>
      {children}
    </div>
  )
}
